name: setup-node
description: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-node20-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies (npm, legacy peers) 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci --legacy-peer-deps
